schemaVersion: 2.1.0
metadata:
   name: helloworld-example
components:
  - name: dev-tooling
    container:
      image: registry.access.redhat.com/ubi9/ubi:latest
      args: ['tail', '-f', '/dev/null']
