schemaVersion: 2.1.0
metadata:
   name: helloworld-example
components:
  - name: dev-tooling
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      memoryLimit: 6G
      memoryRequest: 512Mi
      cpuRequest: 1000m
      cpuLimit: 4000m
      mountSources: true
